### ISSUE TITLE
No connectivity among the hosts

### ISSUE THREAD

**Issue by dragonxtek** [TUDelftNAS/SDN-ResilientMulticast#1]
I don't have connectivity among my hosts.
Do you have a particular topology to test it?

**Comment by Jorik0** [comment]
Are you using MiniNet? It should at the very least be working for all build-in topologies. What settings do you use?

By the way. This app only supports multicast (IPv4) messages with IGMPv3 group messages for joining or leaving groups (unicast could easily be handled by using other apps, or by extending this one). Could you be testing for connectivity by sending unicast packets?

**Comment by dragonxtek** [comment]
Yes, I'm using mininet 2.3.0d1
I tested multicast traffic with iperf, but I don't see traffic on server side

![selection_038](https://cloud.githubusercontent.com/assets/10552658/24152155/993c7472-0e29-11e7-9276-09482cd5d19b.png)
![selection_037](https://cloud.githubusercontent.com/assets/10552658/24152157/999ca748-0e29-11e7-9cba-36ed0ca0b194.png)

I used the same commands for ryu.app.simple_switch_stp_13 and it works without problems.
I have the following topology:

![selection_042](https://cloud.githubusercontent.com/assets/10552658/24152835/8ebd4e48-0e2b-11e7-8dcd-7eacdd7b8373.png)

The strange thing is that in s7-eth1 (that connect to h1) I can see multicast traffic coming from h0

![selection_039](https://cloud.githubusercontent.com/assets/10552658/24152930/d2763032-0e2b-11e7-8d9a-84b9293f975d.png)

Your app detect the multicast group
![selection_041](https://cloud.githubusercontent.com/assets/10552658/24153256/b1d4bd98-0e2c-11e7-92c8-cd25529befb3.png)

**Comment by Jorik0** [comment]
I see the problem. The app creates the group after receiving the first multicast packet. So the earlier join request is ignored (as the group does not yet exist). I don't think this use case occurs often (especially as join-requests are often send multiple times if ignored), but when testing the network/app like this it is a problem.

I'll write a quick fix as soon as possible.

**Comment by Jorik0** [comment]
It should be working properly now. Can you test it again?

**Comment by dragonxtek** [comment]
Now it's working. I can see data on server side, but...
When I run iperf client, appears the following error at ryu app:
```
ADDED/MODDIFIED FLOW FROM SWITCH 2 TO PORTS set([2]) AND set([])
DESTINATION = 225.0.0.5
TAG = 881
Adding backup 7 for 7 in switch 2
FAILED: backup already installed
Adding backup ae:b4:14:17:9f:e3 for ae:b4:14:17:9f:e3 in switch 7
FAILED: backup already installed
Adding backup 7 for 7 in switch 2
MulticastController: Exception occurred during handler processing. Backtrace from offending handler [packet_in_handler] servicing event [EventOFPPacketIn] follows.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ryu/base/app_manager.py", line 290, in _event_loop
    handler(ev)
  File "/home/nboettcher/Downloads/SDN-ResilientMulticast/MulticastController.py", line 863, in packet_in_handler
    self.processMulticast(dp,msg,pkt)
  File "/home/nboettcher/Downloads/SDN-ResilientMulticast/MulticastController.py", line 876, in processMulticast
    self.processIPMulticast(dp,msg,pkt)
  File "/home/nboettcher/Downloads/SDN-ResilientMulticast/MulticastController.py", line 955, in processIPMulticast
    self.builder.add_subscriber(ip.dst, ip.src, subscriber)
  File "/home/nboettcher/Downloads/SDN-ResilientMulticast/AbstractTreeBuilder.py", line 120, in add_subscriber
    if self._process_request(tree, subscriber, True, self.F, ip_group, ip_source):
  File "/home/nboettcher/Downloads/SDN-ResilientMulticast/PerLinkTreeBuilder.py", line 53, in _process_request
    ip_source, backup.graph['tag'], T.graph['tag'], not_done)
  File "/home/nboettcher/Downloads/SDN-ResilientMulticast/MulticastController.py", line 628, in add_backup
    g_id = self._add_group(switch_id, self._parse_buckets_list(in_port, b_group, dp))
  File "/home/nboettcher/Downloads/SDN-ResilientMulticast/MulticastController.py", line 97, in _add_group
    dp.send_msg(cmd)
  File "/usr/local/lib/python2.7/dist-packages/ryu/controller/controller.py", line 347, in send_msg
    msg.serialize()
  File "/usr/local/lib/python2.7/dist-packages/ryu/ofproto/ofproto_parser.py", line 220, in serialize
    self._serialize_body()
  File "/usr/local/lib/python2.7/dist-packages/ryu/ofproto/ofproto_v1_3_parser.py", line 3618, in _serialize_body
    b.serialize(self.buf, offset)
  File "/usr/local/lib/python2.7/dist-packages/ryu/ofproto/ofproto_v1_3_parser.py", line 3551, in serialize
    self.watch_group)
  File "/usr/local/lib/python2.7/dist-packages/ryu/lib/pack_utils.py", line 25, in msg_pack_into
    struct.pack_into(fmt, buf, offset, *args)
error: cannot convert argument to integer
```

**Comment by Jorik0** [comment]
What version of NetworkX are you running?

**Comment by dragonxtek** [comment]
pip show networkx              
Name: networkx
Version: 1.11

**Comment by Jorik0** [comment]
The  app uses weight functions to properly compute (backup) paths. Unfortunately, this feature is currently only supported in the development version of NetworkX.  Which is probably why you are getting these errors. As the path computation functions return completely wrong paths (probably the same backup paths as the primary path, if I look at your output. As it tries to install the port itself as its backup port, which results in some weird behaviour/errors).

If you upgrade your networkx package to the development version it should work.

**Comment by dragonxtek** [comment]
I installed the github version (networkx==2.0.dev20170321173742)
I delete pyc files in the project just in case, but I still have the same error.

**Comment by Jorik0** [comment]
And you are still getting messages like "Adding backup 7 for 7 in switch 2" and "Adding backup ae:b4:14:17:9f:e3 for ae:b4:14:17:9f:e3"? i.e. identical backup?

Because if so, it seems like something is still going wrong with the backup path calculations and python might still be using the older version of networkx instead of the newer one.

**Comment by dragonxtek** [comment]
Yes, I have the same error and I check that networkx version is the developer:
```
Adding backup 6e:b2:c5:8b:57:2f for 6e:b2:c5:8b:57:2f in switch 8
FAILED: backup already installed
Adding backup 6e:b2:c5:8b:57:2f for 6e:b2:c5:8b:57:2f in switch 8
FAILED: backup already installed
Adding backup 3 for 3 in switch 2
Added group 38 to switch 2
ADDED/MODDIFIED FLOW FROM SWITCH 2 TO PORTS set([2]) AND set([])
DESTINATION = 225.0.0.5
TAG = 285
Added backup for 3 to switch 2
From tag 565 to tag 881
ADDED/MODDIFIED FLOW FROM SWITCH 8 TO PORTS set([]) AND set([1])
DESTINATION = 225.0.0.5
TAG = 881
ADDED/MODDIFIED FLOW FROM SWITCH 3 TO PORTS set([2]) AND set([])
DESTINATION = 225.0.0.5
TAG = 881
Adding backup 8 for 8 in switch 3
FAILED: backup already installed
Adding backup 6e:b2:c5:8b:57:2f for 6e:b2:c5:8b:57:2f in switch 8
FAILED: backup already installed
Adding backup 8 for 8 in switch 3
MulticastController: Exception occurred during handler processing. Backtrace from offending handler [packet_in_handler] servicing event [EventOFPPacketIn] follows.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ryu/base/app_manager.py", line 290, in _event_loop
    handler(ev)
  File "/home/nboettcher/Downloads/SDN-ResilientMulticast/MulticastController.py", line 863, in packet_in_handler
    self.processMulticast(dp,msg,pkt)
  File "/home/nboettcher/Downloads/SDN-ResilientMulticast/MulticastController.py", line 876, in processMulticast
    self.processIPMulticast(dp,msg,pkt)
  File "/home/nboettcher/Downloads/SDN-ResilientMulticast/MulticastController.py", line 955, in processIPMulticast
    self.builder.add_subscriber(ip.dst, ip.src, subscriber)
  File "/home/nboettcher/Downloads/SDN-ResilientMulticast/AbstractTreeBuilder.py", line 120, in add_subscriber
    if self._process_request(tree, subscriber, True, self.F, ip_group, ip_source):
  File "/home/nboettcher/Downloads/SDN-ResilientMulticast/PerLinkTreeBuilder.py", line 53, in _process_request
    ip_source, backup.graph['tag'], T.graph['tag'], not_done)
  File "/home/nboettcher/Downloads/SDN-ResilientMulticast/MulticastController.py", line 628, in add_backup
    g_id = self._add_group(switch_id, self._parse_buckets_list(in_port, b_group, dp))
  File "/home/nboettcher/Downloads/SDN-ResilientMulticast/MulticastController.py", line 97, in _add_group
    dp.send_msg(cmd)
  File "/usr/local/lib/python2.7/dist-packages/ryu/controller/controller.py", line 347, in send_msg
    msg.serialize()
  File "/usr/local/lib/python2.7/dist-packages/ryu/ofproto/ofproto_parser.py", line 220, in serialize
    self._serialize_body()
  File "/usr/local/lib/python2.7/dist-packages/ryu/ofproto/ofproto_v1_3_parser.py", line 3618, in _serialize_body
    b.serialize(self.buf, offset)
  File "/usr/local/lib/python2.7/dist-packages/ryu/ofproto/ofproto_v1_3_parser.py", line 3551, in serialize
    self.watch_group)
  File "/usr/local/lib/python2.7/dist-packages/ryu/lib/pack_utils.py", line 25, in msg_pack_into
    struct.pack_into(fmt, buf, offset, *args)
error: cannot convert argument to integer
^C^CTraceback (most recent call last):
  File "/usr/local/bin/ryu-manager", line 11, in <module>
    load_entry_point('ryu==4.9', 'console_scripts', 'ryu-manager')()
  File "/usr/local/lib/python2.7/dist-packages/ryu/cmd/manager.py", line 94, in main
    app_mgr.close()
  File "/usr/local/lib/python2.7/dist-packages/ryu/base/app_manager.py", line 549, in close
    self.uninstantiate(app_name)
  File "/usr/local/lib/python2.7/dist-packages/ryu/base/app_manager.py", line 533, in uninstantiate
    app.stop()
  File "/usr/local/lib/python2.7/dist-packages/ryu/base/app_manager.py", line 185, in stop
    hub.joinall(self.threads)
  File "/usr/local/lib/python2.7/dist-packages/ryu/lib/hub.py", line 99, in joinall
    t.wait()
  File "/usr/local/lib/python2.7/dist-packages/eventlet/greenthread.py", line 175, in wait
    return self._exit_event.wait()
  File "/usr/local/lib/python2.7/dist-packages/eventlet/event.py", line 121, in wait
    return hubs.get_hub().switch()
  File "/usr/local/lib/python2.7/dist-packages/eventlet/hubs/hub.py", line 294, in switch
    return self.greenlet.switch()
  File "/usr/local/lib/python2.7/dist-packages/eventlet/hubs/hub.py", line 346, in run
    self.wait(sleep_time)
  File "/usr/local/lib/python2.7/dist-packages/eventlet/hubs/poll.py", line 85, in wait
    presult = self.do_poll(seconds)
  File "/usr/local/lib/python2.7/dist-packages/eventlet/hubs/epolls.py", line 62, in do_poll
    return self.poll.poll(seconds)
KeyboardInterrupt
 ✘ ✝  ~/Downloads/networkx   master±  python
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import networkx
>>> print networkx.__version__
2.0.dev_20170321173742
```

**Comment by Jorik0** [comment]
Hmmm. It's a bit hard to diagnose this problem, as iperf and this app seem to work fine on my machine.

Can you share your ryu version and the exact commands you are using (i.e. to start the controller, mininet and iperf)?

Do you have the same problem on other simpler topologies? Or only on this one?

**Comment by dragonxtek** [comment]
Now it works!
```
no backup path from 5 to 36:a0:91:99:4e:4e
no backup path from 4 to 36:a0:91:99:4e:4e
no backup path from 1 to 36:a0:91:99:4e:4e
no backup path from 6 to 36:a0:91:99:4e:4e
no backup path from 7 to 36:a0:91:99:4e:4e
no backup path from 8 to 36:a0:91:99:4e:4e
36:a0:91:99:4e:4e added to group ('225.0.0.5', '10.0.0.1')
Received ethernet packet
From 36:a0:91:99:4e:4e to 01:00:5e:00:00:16
IPV4 Multicast Message
Record change for group 225.0.0.5
```
I print networkx.__version__ inside your ryu app, and networkx 1.1 still appeared
I had to uninstall networkx 1.1 with 

> pip uninstall networkx

 and after install networkx 2.0 dev through 

> python setup.py install
